name: Packer
on:
  workflow_dispatch:
    inputs:
      k3s:
        required: true
        type: boolean
      lb:
        required: true
        type: boolean
      pritunl:
        required: true
        type: boolean
jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.15.3"
      - run: rm hcl/pritunl.pkr.hcl
        if: ${{ inputs.pritunl == false }}
      - run: rm hcl/k3s-lb-master.pkr.hcl
        if: ${{ inputs.k3s-lb-master == false }}
      - run: rm hcl/k3s-lb-backup.pkr.hcl
        if: ${{ inputs.k3s-lb-backup == false }}
      - name: Init
        run: packer init hcl
      - name: Lint
        run: packer fmt -check hcl
      - name: Validate
        run: packer validate hcl
      - name: Build
        run: packer build hcl
