name: Packer
on:
  workflow_dispatch:
jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.15.3"
      - name: Init
        run: packer init .
      - name: Lint
        run: packer fmt -check .
      - name: Validate
        run: packer validate .
      - name: Build
        run: packer build .
